#!/usr/bin/env python3
"""
Generate carrier_logos.py file by scanning all logo images and converting to base64.

This script:
1. Scans insurance_server_python/assets/images/ for logo files
2. Converts each to base64 data URI
3. Generates the complete carrier_logos.py file with all mappings

Usage:
    python3 insurance_server_python/utils/generate_carrier_logos.py

The script will automatically:
- Find all .png, .jpg, .jpeg, .svg, .webp files in assets/images/
- Convert them to base64
- Generate constant names from filenames (e.g., mercury-logo.png → MERCURY_LOGO)
- Create carrier name mappings (e.g., "Mercury Insurance", "Mercury Auto Insurance")
- Write the complete carrier_logos.py file
"""

import base64
import re
from pathlib import Path
from typing import Dict, List, Tuple


def image_to_base64(image_path: Path) -> str:
    """Convert an image file to a base64 data URI."""
    # Determine MIME type from extension
    ext = image_path.suffix.lower()
    mime_types = {
        '.png': 'image/png',
        '.jpg': 'image/jpeg',
        '.jpeg': 'image/jpeg',
        '.svg': 'image/svg+xml',
        '.webp': 'image/webp',
    }
    mime_type = mime_types.get(ext, 'image/png')

    # Read and encode the image
    with open(image_path, 'rb') as f:
        image_data = f.read()

    base64_data = base64.b64encode(image_data).decode('utf-8')
    return f"data:{mime_type};base64,{base64_data}"


def filename_to_constant_name(filename: str) -> str:
    """Convert a filename to a Python constant name.

    Examples:
        mercury-logo.png → MERCURY_LOGO
        progressive.png → PROGRESSIVE_LOGO
        state-farm.png → STATE_FARM_LOGO
    """
    # Remove extension
    name = Path(filename).stem
    # Replace hyphens and spaces with underscores
    name = name.replace('-', '_').replace(' ', '_')
    # Convert to uppercase
    name = name.upper()
    # Ensure it ends with _LOGO
    if not name.endswith('_LOGO'):
        name = f"{name}_LOGO"
    return name


def filename_to_carrier_names(filename: str) -> List[str]:
    """Generate likely carrier name variations from a filename.

    Examples:
        mercury-logo.png → ["Mercury", "Mercury Insurance", "Mercury Auto Insurance"]
        progressive.png → ["Progressive", "Progressive Insurance"]
        state-farm.png → ["State Farm", "State Farm Insurance"]
    """
    # Remove extension and -logo suffix
    name = Path(filename).stem
    name = re.sub(r'-logo$', '', name, flags=re.IGNORECASE)

    # Convert hyphens to spaces and title case
    base_name = name.replace('-', ' ').replace('_', ' ').title()

    # Generate variations
    variations = [
        base_name,
        f"{base_name} Insurance",
    ]

    # Add "Auto Insurance" variation for common carriers
    if base_name.lower() in ['mercury', 'geico', 'progressive', 'allstate', 'state farm']:
        variations.append(f"{base_name} Auto Insurance")

    # Remove duplicates while preserving order
    seen = set()
    unique_variations = []
    for var in variations:
        if var not in seen:
            seen.add(var)
            unique_variations.append(var)

    return unique_variations


def scan_logo_directory(images_dir: Path) -> List[Tuple[str, Path]]:
    """Scan the images directory for logo files.

    Returns:
        List of (constant_name, file_path) tuples
    """
    supported_extensions = {'.png', '.jpg', '.jpeg', '.svg', '.webp'}
    logo_files = []

    for file_path in sorted(images_dir.glob('*')):
        if file_path.suffix.lower() in supported_extensions:
            constant_name = filename_to_constant_name(file_path.name)
            logo_files.append((constant_name, file_path))

    return logo_files


def generate_carrier_logos_file(output_path: Path, logo_files: List[Tuple[str, Path]]):
    """Generate the complete carrier_logos.py file."""

    with open(output_path, 'w') as f:
        # Write header
        f.write('"""')
        f.write('\nCarrier logo database - Base64-encoded data URIs for insurance carrier logos.')
        f.write('\n')
        f.write('\nAUTO-GENERATED FILE - DO NOT EDIT MANUALLY')
        f.write('\nGenerated by: insurance_server_python/utils/generate_carrier_logos.py')
        f.write('\n')
        f.write('\nTo regenerate this file:')
        f.write('\n    python3 insurance_server_python/utils/generate_carrier_logos.py')
        f.write('\n"""')
        f.write('\n\n')

        # Write individual logo constants
        f.write('# Individual carrier logos (base64 data URIs)\n')
        f.write('# These are automatically generated from files in assets/images/\n\n')

        carrier_mappings: Dict[str, str] = {}

        for constant_name, file_path in logo_files:
            print(f"Converting {file_path.name} → {constant_name}...")

            try:
                base64_uri = image_to_base64(file_path)

                # Write the constant (wrapped for readability if needed)
                f.write(f'# Generated from: {file_path.name}\n')
                f.write(f'{constant_name} = "{base64_uri}"\n\n')

                # Generate carrier name variations
                carrier_names = filename_to_carrier_names(file_path.name)
                for carrier_name in carrier_names:
                    carrier_mappings[carrier_name] = constant_name

            except Exception as e:
                print(f"  ⚠️  Error processing {file_path.name}: {e}")
                # Write a placeholder
                f.write(f'# ERROR: Failed to convert {file_path.name}\n')
                f.write(f'{constant_name} = ""\n\n')

        # Write carrier mappings dictionary
        f.write('\n# Carrier name mappings\n')
        f.write('# Maps carrier names (as returned by rating API) to their logo constants\n')
        f.write('CARRIER_LOGOS = {\n')

        for carrier_name, constant_name in sorted(carrier_mappings.items()):
            f.write(f'    "{carrier_name}": {constant_name},\n')

        f.write('}\n\n')

        # Write helper function
        f.write('''
def get_carrier_logo(carrier_name: str) -> str:
    """
    Get the logo for a carrier by name.
    Returns empty string if carrier not found (widget will show text fallback).

    Args:
        carrier_name: Name of the insurance carrier

    Returns:
        Base64 data URI for the carrier's logo, or empty string
    """
    # Try exact match first
    if carrier_name in CARRIER_LOGOS:
        return CARRIER_LOGOS[carrier_name]

    # Try fuzzy match
    normalized = carrier_name.lower()
    for key, logo in CARRIER_LOGOS.items():
        if key.lower() in normalized or normalized in key.lower():
            return logo

    # Return empty string (widget will show text fallback)
    return ""
''')

    print(f"\n✅ Generated {output_path}")
    print(f"   - {len(logo_files)} logo files processed")
    print(f"   - {len(carrier_mappings)} carrier name mappings created")


def main():
    """Main entry point."""
    # Determine paths
    script_dir = Path(__file__).parent
    project_root = script_dir.parent.parent
    images_dir = project_root / "insurance_server_python" / "assets" / "images"
    output_file = project_root / "insurance_server_python" / "carrier_logos.py"

    print("🔍 Scanning for logo files...")
    print(f"   Images directory: {images_dir}")
    print(f"   Output file: {output_file}\n")

    if not images_dir.exists():
        print(f"❌ Error: Images directory not found: {images_dir}")
        print("   Please create it and add logo files.")
        return 1

    # Scan for logo files
    logo_files = scan_logo_directory(images_dir)

    if not logo_files:
        print(f"⚠️  No logo files found in {images_dir}")
        print("   Supported formats: .png, .jpg, .jpeg, .svg, .webp")
        return 1

    print(f"Found {len(logo_files)} logo files:\n")
    for constant_name, file_path in logo_files:
        size_kb = file_path.stat().st_size / 1024
        print(f"  • {file_path.name} ({size_kb:.1f} KB) → {constant_name}")
    print()

    # Generate the file
    print("🔄 Converting images to base64 and generating carrier_logos.py...\n")
    generate_carrier_logos_file(output_file, logo_files)

    print("\n✨ Done! You can now use the logos in your application.")
    print("\nExample carrier mappings created:")

    # Show a few example mappings
    for constant_name, file_path in logo_files[:3]:
        carrier_names = filename_to_carrier_names(file_path.name)
        for carrier_name in carrier_names[:2]:  # Show first 2 variations
            print(f'  "{carrier_name}" → {constant_name}')

    if len(logo_files) > 3:
        print(f"  ... and {len(logo_files) - 3} more carriers")

    return 0


if __name__ == "__main__":
    exit(main())
